//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FinanceModel", "FK_Data_Data", "Symbol", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Finance.Symbol), "Data", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Finance.Datum), true)]

#endregion

namespace Finance
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FinanceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FinanceEntities object using the connection string found in the 'FinanceEntities' section of the application configuration file.
        /// </summary>
        public FinanceEntities() : base("name=FinanceEntities", "FinanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FinanceEntities object.
        /// </summary>
        public FinanceEntities(string connectionString) : base(connectionString, "FinanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FinanceEntities object.
        /// </summary>
        public FinanceEntities(EntityConnection connection) : base(connection, "FinanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Datum> Data
        {
            get
            {
                if ((_Data == null))
                {
                    _Data = base.CreateObjectSet<Datum>("Data");
                }
                return _Data;
            }
        }
        private ObjectSet<Datum> _Data;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Symbol> Symbols
        {
            get
            {
                if ((_Symbols == null))
                {
                    _Symbols = base.CreateObjectSet<Symbol>("Symbols");
                }
                return _Symbols;
            }
        }
        private ObjectSet<Symbol> _Symbols;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToData(Datum datum)
        {
            base.AddObject("Data", datum);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Symbols EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSymbols(Symbol symbol)
        {
            base.AddObject("Symbols", symbol);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="Datum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Datum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Datum object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="symbolId">Initial value of the SymbolId property.</param>
        public static Datum CreateDatum(global::System.Int32 id, global::System.Int32 symbolId)
        {
            Datum datum = new Datum();
            datum.Id = id;
            datum.SymbolId = symbolId;
            return datum;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SymbolId
        {
            get
            {
                return _SymbolId;
            }
            set
            {
                OnSymbolIdChanging(value);
                ReportPropertyChanging("SymbolId");
                _SymbolId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SymbolId");
                OnSymbolIdChanged();
            }
        }
        private global::System.Int32 _SymbolId;
        partial void OnSymbolIdChanging(global::System.Int32 value);
        partial void OnSymbolIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LTP
        {
            get
            {
                return _LTP;
            }
            set
            {
                OnLTPChanging(value);
                ReportPropertyChanging("LTP");
                _LTP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LTP");
                OnLTPChanged();
            }
        }
        private Nullable<global::System.Decimal> _LTP;
        partial void OnLTPChanging(Nullable<global::System.Decimal> value);
        partial void OnLTPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Time;
        partial void OnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Volume;
        partial void OnVolumeChanging(Nullable<global::System.Decimal> value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Ask
        {
            get
            {
                return _Ask;
            }
            set
            {
                OnAskChanging(value);
                ReportPropertyChanging("Ask");
                _Ask = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ask");
                OnAskChanged();
            }
        }
        private Nullable<global::System.Decimal> _Ask;
        partial void OnAskChanging(Nullable<global::System.Decimal> value);
        partial void OnAskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Bid
        {
            get
            {
                return _Bid;
            }
            set
            {
                OnBidChanging(value);
                ReportPropertyChanging("Bid");
                _Bid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bid");
                OnBidChanged();
            }
        }
        private Nullable<global::System.Decimal> _Bid;
        partial void OnBidChanging(Nullable<global::System.Decimal> value);
        partial void OnBidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> High
        {
            get
            {
                return _High;
            }
            set
            {
                OnHighChanging(value);
                ReportPropertyChanging("High");
                _High = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High");
                OnHighChanged();
            }
        }
        private Nullable<global::System.Decimal> _High;
        partial void OnHighChanging(Nullable<global::System.Decimal> value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Low
        {
            get
            {
                return _Low;
            }
            set
            {
                OnLowChanging(value);
                ReportPropertyChanging("Low");
                _Low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Low");
                OnLowChanged();
            }
        }
        private Nullable<global::System.Decimal> _Low;
        partial void OnLowChanging(Nullable<global::System.Decimal> value);
        partial void OnLowChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK_Data_Data", "Symbol")]
        public Symbol Symbol
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("FinanceModel.FK_Data_Data", "Symbol").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("FinanceModel.FK_Data_Data", "Symbol").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Symbol> SymbolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Symbol>("FinanceModel.FK_Data_Data", "Symbol");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Symbol>("FinanceModel.FK_Data_Data", "Symbol", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="Symbol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Symbol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Symbol object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Symbol CreateSymbol(global::System.Int32 id)
        {
            Symbol symbol = new Symbol();
            symbol.Id = id;
            return symbol;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK_Data_Data", "Data")]
        public EntityCollection<Datum> Data
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Datum>("FinanceModel.FK_Data_Data", "Data");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Datum>("FinanceModel.FK_Data_Data", "Data", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
